version: '3.9'
services:
    db-estagio:
        container_name: db-estagio-dev
        image: postgres:14.2-alpine
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_MULTIPLE_DATABASES: "klok_dev_est_api_1,klok_dev_est_api_2"
            POSTGRES_USER: "klok_dev_est"
            POSTGRES_PASSWORD: "klokdevest"
        volumes:
            - ./sql-init:/docker-entrypoint-initdb.d
            - ./sql-init/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
            - ./db:/var/lib/postgresql/data
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.7.5-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: klok_dev_est
            RABBITMQ_DEFAULT_PASS: klokdevest

    klok_service_a:
        container_name: klok_service_a
        image: openjdk:17-alpine
        ports:
            - "8080:8080"
        command: java -Duser.timezone=GMT-03:00 -Xmx512m -Xmx256m -jar /executable/klok-service-a.jar
        depends_on:
            - db-estagio
            - rabbitmq
        volumes:
            - ./desafio_estagio_klok_tech_api_1/target/challenge-0.1-SNAPSHOT.jar:/executable/klok-service-a.jar
        links:
            - db-estagio
            - rabbitmq
    
    klok_service_b:
        container_name: klok_service_b
        image: openjdk:17-alpine
        ports:
            - "8181:8181"
        command: java -Duser.timezone=GMT-03:00 -Xmx512m -Xmx256m -jar /executable/klok_service_b.jar

        depends_on:
            - db-estagio
            - rabbitmq
         
        volumes:
            - ./desafio_estagio_klok_tech_api_2/target/challenge-0.1-SNAPSHOT.jar:/executable/klok_service_b.jar
        links:
            - db-estagio
            - rabbitmq
